### ISSUE TITLE
Quick start

### ISSUE THREAD

**Issue by Xingyu-Lin** [mcorah/scholar_email_process#1]
Could you write a simple readme on how to use this repo? For example, I am getting an error which is `missing credentials.json` and I am not familiar on the google authentication...

**Comment by mcorah** [comment]
Hey, I'm new to the Google API and how they use credentials. I'll try to push an update shortly.

**Comment by mcorah** [comment]
Ok. I've pushed a brief update with instructions linking to the Python Gmail Quickstart.

I'm not sure if it would be kosher to publish application credentials or if I am somehow handling authentication incorrectly so this is probably the safest bet for now.

Also, to my knowledge, you would be the first person to use this other than me. So, would you mind letting me know if this script works for you afterward?
